import math
 

s = 'GUAGCUAUUAGCCGUAUAUAUAGCGCGCACGGUGGUCCGGACGCUAUCGACGCAAUUGCAGCCCUAACGCGUUAGUGUAUACUCGUAUAAACUAGAUUUAAAGUUAACCGUUACUCCAUGCGGUAAGAUGUACAUCAUAAUUCGGCGCCUAGGCGCUGUCGAGCCCAGCUAACGUUUUACGAGCGAUAGCUUAGGUACCACGUAACGUGCUAUACGUAAUUACAAUUGAUCGAUGUAGCAUUUAAUAUAUACUUGCAAUCUCGAGGUCGAUAUCGACAGCAAUUGC'

au = s.count('A') 
gc = s.count('G') 
n = au + gc
divider = math.factorial((n + 1)) * (math.factorial(n))
x = math.factorial((2*n))/divider
print(x % 1000000)


